spring:
  application:
    name: Inventory Service
  boot:
    admin:
      client:
        url:  http://localhost:9090
        enabled: true
        auto-registration: true
        instance:
          name: ${spring.application.name:JSS}
  cache:
    type: caffeine
    cache-names: products
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m
#kafka localhost
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    eshop-dao: DEBUG
    eshop-controller: INFO
    eshop: INFO

  group:
    spring: "org.springframework, org.springdoc"
    eshop-dao: "com.inventory.repository"
    eshop-controller: "com.inventory.controller"
    eshop: "com.inventory.model"

server:
  tomcat:
    threads:
      max: 5
    max-connections: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    configprops:
      show-values: always
    env:
      show-values: always
    loggers:
      enabled: true
#eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

  #promites config
  server:
    port: ${server.port:8006}
    web:
      exposure:
        include: health,info,prometheus
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
      health:
        show-details: always

