server:
  port: 8089

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Notification-Service
          uri: lb://Notification-Service
          predicates:
            - Path=/notification/**
        - id: Order-Service
          uri: lb://Order-Service
          predicates:
            - Path=/order/**
        - id: Inventory-Service
          uri: lb://Inventory-Service
          predicates:
            - Path=/inventory/**
        - id: Payment-Service
          uri: lb://Payment-Service
          predicates:
            - Path=/payment/**
        - id: Product-Service
          uri: lb://Product-Service
          predicates:
            - Path=/product/**
        - id: Security-Service
          uri: lb://Security-Service
          predicates:
            - Path=/security/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

filters:
  - AddRequestHeader=X-Request-ID, ${random.uuid}
  - name: RequestRateLimiter
    args:
      redis-rate-limiter.replenishRate: 10
      redis-rate-limiter.burstCapacity: 20

