apiVersion: apps/v1
kind: Deployment
metadata:
  name: SpringBootAdmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: SpringBootAdmin
  template:
    metadata:
      labels:
        app: SpringBootAdmin
    spec:
      containers:
        - name: SpringBootAdmin
          image: SpringBootAdmin
          ports:
            - containerPort: 9090
