apiVersion: apps/v1
kind: Deployment
metadata:
  name: SpringBootAdmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-admin-dashboard
  template:
    metadata:
      labels:
        app: spring-admin-dashboard
    spec:
      containers:
        - name: spring-admin-dashboard
          image: spring-admin-dashboard
          ports:
            - containerPort: 9090
